### ISSUE TITLE
Feature Request: Dutch Shows in overview

### ISSUE THREAD

**Issue by derkens** [Mickroz/what2watch#7]
Since it is such a nice overview to keep track of what needs watching, it would be nice if Dutch TV shows could be included. There missing now due to no subtitles :)

**Comment by Mickroz** [comment]
already implemented, see Settings -> Skip Shows

**Comment by derkens** [comment]
so.. 'skip show' doesnt skip the show, but skips the check for a presence of a subtitle file.
thanks

**Comment by Mickroz** [comment]
correct.
